remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Rahul Bakshee
# logo: /assets/img/logo.png
description: > 
  Machine Learning Engineer | Data Scientist | Software Engineering | Cloud | Artificial Intelligence | Omnichannel
  <br><br>
  Experienced in building large-scale AI/ML solutions, with expertise in Deep Learning, NLP, and Generative AI (LLMs, RAG, LangChain). Proven impact through innovative model deployment, boosting revenue, reducing costs, and accelerating healthcare solutions. Adept in Python, TensorFlow, PyTorch, MLOps, and cloud platforms (AWS, GCP, Azure), delivering business value with cutting-edge AI.

<a href="https://www.linkedin.com/in/rahulbakshee/"></a> 

# show_downloads: true
# google_analytics: your Google Analytics tracking ID here
theme: jekyll-theme-minimal
